import Foundation
import AEPMessagingLiveActivity
import ActivityKit

// This demo shows how the AttributeMetadataMacro would be used with LiveActivity

// First, define the protocol for exposing metadata (normally this would be in the SDK)
@available(iOS 16.1, *)
public protocol _ExposesMetadata {
    static var __metadata: PropertyMetadata { get }
}

// The PropertyMetadata structure to hold property information
@available(iOS 16.1, *)
public struct PropertyMetadata {
    public var properties: [(name: String, type: Any.Type)]
    
    public func expanded() -> String {
        return properties.map { "(\"\($0.name)\", \(String(describing: $0.type)))" }.description
    }
}

// Simulating the macro implementation by manually creating the same structure that
// the macro would generate at compile time
@available(iOS 16.1, *)
struct AirplaneTrackingAttributes: LiveActivityAttributes, _ExposesMetadata {
    var liveActivityData: LiveActivityData
    
    // Static attributes
    let arrivalAirport: String
    let departureAirport: String
    let arrivalTerminal: String
    
    // Nested struct example
    let exampleStruct: ExampleStruct
    
    // Normally generated by the macro, here manually implemented
    static var __metadata: PropertyMetadata {
        return PropertyMetadata(properties: [
            ("liveActivityData", LiveActivityData.self),
            ("arrivalAirport", String.self),
            ("departureAirport", String.self),
            ("arrivalTerminal", String.self),
            ("exampleStruct.nestedString", String.self),
            ("exampleStruct.nestedInt", Int.self),
            ("exampleStruct.nestedBool", Bool.self)
        ])
    }
    
    // ContentState also implements _ExposesMetadata
    struct ContentState: Codable, Hashable, _ExposesMetadata {
        let journeyProgress: Int
        
        // Normally generated by the macro, here manually implemented
        static var __metadata: PropertyMetadata {
            return PropertyMetadata(properties: [
                ("journeyProgress", Int.self)
            ])
        }
    }
}

// Example of a nested struct that also exposes metadata
@available(iOS 16.1, *)
struct ExampleStruct: Codable, _ExposesMetadata {
    let nestedString: String
    let nestedInt: Int
    let nestedBool: Bool
    
    // Normally generated by the macro, here manually implemented
    static var __metadata: PropertyMetadata {
        return PropertyMetadata(properties: [
            ("nestedString", String.self),
            ("nestedInt", Int.self),
            ("nestedBool", Bool.self)
        ])
    }
}

// Utility function to demonstrate accessing metadata (would be used in your app)
@available(iOS 16.1, *)
func debugDumpAttributes<T: LiveActivityAttributes>(_: T.Type) -> String {
    var output = ""
    
    // ------- static part -------
    if let provider = T.self as? _ExposesMetadata.Type {
        output += "🟢 \(T.self) static properties:\n"
        output += provider.__metadata.expanded() + "\n"
    } else {
        output += "⚪️ \(T.self) has no compile-time metadata\n"
    }
    
    // ------- ContentState -------
    if let provider = T.ContentState.self as? _ExposesMetadata.Type {
        output += "🟢 \(T.ContentState.self) properties:\n"
        output += provider.__metadata.expanded() + "\n"
    } else {
        output += "⚪️ \(T.ContentState.self) has no compile-time metadata\n"
    }
    
    return output
}

// Example usage:
// let metadataInfo = debugDumpAttributes(AirplaneTrackingAttributes.self)
// print(metadataInfo)
// 
// Expected output:
// 🟢 AirplaneTrackingAttributes static properties:
// [("liveActivityData", AEPMessagingLiveActivity.LiveActivityData), ("arrivalAirport", Swift.String), ("departureAirport", Swift.String), ("arrivalTerminal", Swift.String), ("exampleStruct.nestedString", Swift.String), ("exampleStruct.nestedInt", Swift.Int), ("exampleStruct.nestedBool", Swift.Bool)]
// 🟢 ContentState properties:
// [("journeyProgress", Swift.Int)] 